# Generated by Django 5.2.6 on 2025-11-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_host', models.CharField(db_index=True, max_length=100, unique=True)),
                ('range_up', models.FloatField(default=0)),
                ('range_down', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits', to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source_host', models.CharField(db_index=True, max_length=100)),
                ('min_value', models.FloatField()),
                ('avg_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('stddev_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.circuit')),
            ],
            options={
                'verbose_name': 'Server Log',
                'verbose_name_plural': 'Server Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'source_host', 'circuit'], name='api_serverl_timesta_e0068d_idx')],
                'constraints': [models.UniqueConstraint(fields=('timestamp', 'source_host', 'circuit'), name='unique_log_entry')],
            },
        ),
    ]
